# Generated by Django 4.2.11 on 2024-12-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_appointments_car_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='car_color',
            field=models.CharField(default='Black', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='car_regi_num',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
