# Generated by Django 4.2.11 on 2024-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_appointments_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='car_regi_num',
            field=models.CharField(max_length=200),
        ),
    ]
